// `/deploy` subpath — the deploy/lifecycle value surface: the 3 on-chain tx free-fns
// + `executeTx` (core), the `LeaseState` runtime enum + its JSON converters (core,
// browser-safe), and fred's manifest builders, provider clients, fred-lease lifecycle,
// poll/wait helpers, lease-status wait, and ADR-036 auth-token helpers.
// `EncodeObject` is re-exported (type-only) for `executeTx` ergonomics.
import type { EncodeObject } from '@cosmjs/proto-signing';

export {
  type AppDeploySpec,
  type BuildManifestOptions,
  type DeployResult,
  type ExecuteTxResult,
  executeTx,
  type FundCreditsResult,
  fundCredits,
  LeaseState,
  leaseStateFromJSON,
  leaseStateToJSON,
  type ManifestDeploySpec,
  type SetItemCustomDomainInput,
  type SetItemCustomDomainResult,
  type StopAppResult,
  setItemCustomDomain,
  stopApp,
  type TxCallOptions,
} from '@manifest-network/manifest-mcp-core';
export {
  AuthTimestampTracker,
  type AuthTokenPayload,
  appStatus,
  buildManifest,
  buildStackManifest,
  type ConnectionDetails,
  checkedFetch,
  createAuthToken,
  createAuthTokens,
  createLeaseDataSignMessage,
  createProviderAuth,
  createSignMessage,
  type DeployAppInput,
  type DeployAppResult,
  type DeployCallOptions,
  type DeployManifestInput,
  type DeployManifestOptions,
  deployApp,
  deployManifest,
  deriveAppNameFromImage,
  type FredActionResponse,
  type FredAuthCtx,
  type FredInstanceInfo,
  type FredLeaseLogs,
  type FredLeaseProvision,
  type FredLeaseRelease,
  type FredLeaseReleases,
  type FredLeaseStatus,
  type FredReadCtx,
  type FredServiceStatus,
  fetchActiveLease,
  getAppLogs,
  getLeaseConnectionInfo,
  getLeaseLogs,
  getLeaseProvision,
  getLeaseReleases,
  getLeaseStatus,
  getProviderHealth,
  getServiceNames,
  type InstanceInfo,
  isLeaseFailureTerminal,
  isStackManifest,
  isUrlSsrfSafe,
  type LeaseConnectionResponse,
  type LifecycleCallOptions,
  MAX_TAIL,
  mergeManifest,
  metaHashHex,
  normalizePorts,
  type PollOptions,
  PROVISION_FAILED,
  PROVISION_IN_PROGRESS,
  ProviderApiError,
  type ProviderAuthPort,
  type ProviderHealthResponse,
  type ProviderUrlOptions,
  parseStackManifest,
  pollLeaseUntilReady,
  resolveProviderUrl,
  restartApp,
  restartLease,
  type ServiceConfig,
  type ServiceConnectionDetails,
  type SkuSelector,
  type TerminalChainLeaseState,
  type TerminalChainState,
  type TerminalChainStateContext,
  TerminalChainStateError,
  updateApp,
  updateLease,
  uploadLeaseData,
  validateManifest,
  validateProviderUrl,
  validateServiceName,
  type WaitForAppReadyOptions,
  type WaitForAppReadyResult,
  type WaitForLeaseStatusCtx,
  type WaitForLeaseStatusOptions,
  waitForAppReady,
  waitForLeaseStatus,
} from '@manifest-network/manifest-mcp-fred';
export type { EncodeObject };
