// `/deploy` subpath — the deploy/lifecycle value surface: the 3 on-chain tx free-fns
// + `executeTx` (core), the `LeaseState` runtime enum + its JSON converters (core,
// browser-safe), and fred's manifest builders, provider clients, fred-lease lifecycle,
// poll/wait helpers, lease-status wait, and ADR-036 auth-token helpers.
// `EncodeObject` is re-exported (type-only) for `executeTx` ergonomics.
import type { EncodeObject } from '@cosmjs/proto-signing';

export {
  type AppDeploySpec,
  type BuildManifestOptions,
  type DeployResult,
  type ExecuteTxResult,
  executeTx,
  type FredLeaseItem,
  type FundCreditsResult,
  fundCredits,
  LeaseState,
  leaseStateFromJSON,
  leaseStateToJSON,
  type ManifestDeploySpec,
  type SetItemCustomDomainInput,
  type SetItemCustomDomainResult,
  type StopAppResult,
  setItemCustomDomain,
  stopApp,
  type TxCallOptions,
} from '@manifest-network/manifest-mcp-core';
export {
  AuthTimestampTracker,
  type AuthTokenPayload,
  appStatus,
  type BodyReadOptions,
  buildManifest,
  buildStackManifest,
  type ConnectionDetails,
  checkedFetch,
  createAuthToken,
  createAuthTokens,
  createLeaseDataSignMessage,
  createProviderAuth,
  createSignMessage,
  DEFAULT_FETCH_TIMEOUT_MS,
  DEFAULT_MAX_CONSECUTIVE_FAILURES,
  DEFAULT_POLL_TIMEOUT_MS,
  type DeployAppInput,
  type DeployAppResult,
  type DeployCallOptions,
  type DeployManifestInput,
  type DeployManifestOptions,
  deployApp,
  deployManifest,
  deriveAppNameFromImage,
  describeFredFailure,
  type FetchJsonCheckedOptions,
  FRED_FAILURE_REASONS,
  FRED_REASON_GUIDANCE,
  type FredActionResponse,
  type FredAuthCtx,
  type FredFailure,
  type FredFailureActor,
  type FredFailureReason,
  type FredFailureSource,
  type FredInstanceInfo,
  type FredLeaseLogs,
  type FredLeaseProvision,
  type FredLeaseRelease,
  type FredLeaseReleases,
  type FredLeaseStatus,
  type FredReadCtx,
  type FredReasonGuidance,
  type FredServiceStatus,
  failureDetail,
  fetchActiveLease,
  fetchJsonChecked,
  getAppLogs,
  getLeaseConnectionInfo,
  getLeaseLogs,
  getLeaseProvision,
  getLeaseReleases,
  getLeaseStatus,
  getProviderHealth,
  getServiceNames,
  guidanceFor,
  type InstanceInfo,
  isKnownFailureReason,
  isLeaseFailureTerminal,
  isStackManifest,
  isTransientProviderError,
  isUrlSsrfSafe,
  type LeaseConnectionResponse,
  LeaseReadinessUnconfirmedError,
  type LeaseReadinessUnconfirmedInput,
  type LifecycleCallOptions,
  MAX_TAIL,
  mergeManifest,
  metaHashHex,
  normalizePorts,
  type PollOptions,
  PROVISION_FAILED,
  PROVISION_IN_PROGRESS,
  PROVISION_SUCCESS,
  ProviderApiError,
  type ProviderApiErrorOptions,
  type ProviderAuthPort,
  type ProviderErrorKind,
  type ProviderHealthCheck,
  type ProviderHealthResponse,
  type ProviderUrlOptions,
  parseRetryAfterMs,
  parseStackManifest,
  pollLeaseUntilReady,
  type ReadinessUnconfirmedReason,
  type RestoreResult,
  resolveProviderUrl,
  restartApp,
  restartLease,
  restoreApp,
  restoreLease,
  type ServiceConfig,
  type ServiceConnectionDetails,
  type SkuSelector,
  type TerminalChainLeaseState,
  type TerminalChainState,
  type TerminalChainStateContext,
  TerminalChainStateError,
  updateApp,
  updateLease,
  uploadLeaseData,
  validateManifest,
  validateProviderUrl,
  validateServiceName,
  type WaitForAppReadyOptions,
  type WaitForAppReadyResult,
  type WaitForLeaseStatusCtx,
  type WaitForLeaseStatusOptions,
  waitForAppReady,
  waitForLeaseStatus,
} from '@manifest-network/manifest-mcp-fred';
export type { EncodeObject };
