import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  bundleForBrowser,
  findNodeOnlyImports,
  hasWebCryptoFallback,
  unallowedBrowserWarnings,
} from '../../../tools/browser-bundle.js';

/**
 * The REAL `default:null`-chain guard (B1-secondary; ENG-309).
 *
 * The Node-run barrel-hygiene tests (`../src/index.test.ts`) resolve under the `node`
 * condition, so they PASS even if a browser-safe barrel statically pulls a module whose
 * browser resolution is `default:null` (core's `/guarded-fetch`, agent-core's
 * `/guarded-fetch`). That failure is invisible to vitest and to dependency-cruiser
 * (`doNotFollow:node_modules`). The ONLY thing that catches it is an actual
 * browser-condition bundle: `platform:'browser'` defaults `conditionNames` to
 * `['import','browser','default']` (the `node` condition is NOT applied), so a
 * `default:null` mapping throws a resolution error mid-bundle.
 *
 * This bundles EACH browser-safe SDK subpath through its public package specifier and
 * asserts that the build succeeds without an unguarded Node import; each node-only entry
 * must reject. A separate local-file control bypasses the SDK map and proves a transitive
 * dependency's `default:null` still hard-fails. Requires `dist/` built first
 * (`npm run build -w @manifest-network/manifest-sdk`).
 */

/** Package root, the base the `exports` map's `./dist/*.js` paths are relative to. */
const PKG_ROOT = new URL('../', import.meta.url);

type Entry = { subpath: string; specifier: string };

/**
 * Split the SDK's subpath entries by what `package.json` itself says about browser resolution
 * (ENG-644). DERIVED, never hand-listed: a hand-maintained entry list silently stops covering a
 * newly added subpath, which is the drift that made the dependency-cruiser DAG rules vacuous
 * (ENG-641). The discriminator is not a convention — `default: null` IS the browser fence, the
 * exact mapping that makes browser resolution throw, so a new entry lands on the correct side by
 * construction.
 */
function subpathEntries(): { browserSafe: Entry[]; nodeOnly: Entry[] } {
  const { name, exports } = JSON.parse(
    readFileSync(new URL('package.json', PKG_ROOT), 'utf8'),
  ) as { name: string; exports: Record<string, unknown> };

  const browserSafe: Entry[] = [];
  const nodeOnly: Entry[] = [];
  for (const [subpath, conditions] of Object.entries(exports)) {
    // `./package.json` maps to a bare string, not a condition object — not a JS entry.
    if (typeof conditions !== 'object' || conditions === null) continue;
    const {
      import: esm,
      node,
      default: fallback,
    } = conditions as Record<string, unknown>;
    // Require a concrete runtime target. The bundle itself resolves the public specifier so the
    // package map — including its browser fence — remains part of the test.
    const target = [esm, node].find(
      (condition) => typeof condition === 'string',
    ) as string | undefined;
    if (!target) continue;
    const specifier = subpath === '.' ? name : `${name}${subpath.slice(1)}`;
    (fallback === null ? nodeOnly : browserSafe).push({
      subpath,
      specifier,
    });
  }
  return { browserSafe, nodeOnly };
}

const { browserSafe: BROWSER_SAFE, nodeOnly: NODE_ONLY } = subpathEntries();

describe('manifest-sdk browser resolution + Node-builtin hygiene', () => {
  // Anti-vacuity: every assertion below is generated by a loop, so a derivation that silently
  // returned nothing would register ZERO tests and the file would pass green having checked
  // nothing — the precise failure mode this suite exists to prevent.
  it('derives both entry sets from package.json exports (neither is empty)', () => {
    expect(BROWSER_SAFE.length).toBeGreaterThan(0);
    expect(NODE_ONLY.length).toBeGreaterThan(0);
  });

  for (const { subpath, specifier } of BROWSER_SAFE) {
    it(`${subpath} bundles cleanly under browser conditions`, async () => {
      const { code, unresolvedWarnings } = await bundleForBrowser(specifier);
      expect(unallowedBrowserWarnings(unresolvedWarnings)).toEqual([]);
      const leaks = findNodeOnlyImports(code);
      expect(leaks, JSON.stringify(leaks, null, 2)).toEqual([]);
      if (subpath === '.') expect(hasWebCryptoFallback(code)).toBe(true);
    });
  }

  // Public-entry controls prove the SDK's own browser fences remain active.
  for (const { subpath, specifier } of NODE_ONLY) {
    it(`${subpath} REJECTS under browser conditions (SDK default:null fence)`, async () => {
      await expect(bundleForBrowser(specifier)).rejects.toThrow();
    });
  }

  // This deliberately bypasses the SDK exports map. Its only browser fences are
  // transitive (`core/guarded-fetch`, `core/events-node`, and `fred/node`), so it
  // catches a resolver that still rejects entry-level null but stops rejecting a
  // dependency-level `default:null` mapping.
  it('REJECTS a local /node entry through a transitive default:null dependency', async () => {
    const localNodeEntry = new URL('../dist/node.js', import.meta.url).pathname;
    await expect(bundleForBrowser(localNodeEntry)).rejects.toThrow(
      /manifest-mcp-core\/guarded-fetch/,
    );
  });

  it('allows only the exact guarded CosmJS crypto warning', () => {
    const allowed =
      "Could not resolve 'crypto' in node_modules/@cosmjs/crypto/build/pbkdf2.js";
    expect(unallowedBrowserWarnings([allowed])).toEqual([]);
    expect(
      unallowedBrowserWarnings([
        "Could not resolve 'child_process' in node_modules/@cosmjs/crypto/build/pbkdf2.js",
        "Could not resolve 'crypto' in node_modules/other-package/index.js",
      ]),
    ).toHaveLength(2);
  });

  it('detects node: imports, bare builtins, and rolldown __require calls', () => {
    const code = [
      "import 'node:fs';",
      "import('dns');",
      "export { value } from 'zlib';",
      "const one = require('buffer');",
      "const two = __require('child_process');",
      "const three = __require('worker_threads');",
      "const four = require('util');",
      "const five = require('events');",
      "const six = require('url');",
      "const seven = require('assert');",
      "const eight = require('vm');",
      "const nine = require('crypto-browserify');",
    ].join('\n');
    expect(findNodeOnlyImports(code).map(({ specifier }) => specifier)).toEqual(
      [
        'node:fs',
        'dns',
        'zlib',
        'buffer',
        'child_process',
        'worker_threads',
        'util',
        'events',
        'url',
        'assert',
        'vm',
        'crypto-browserify',
      ],
    );
  });

  it('allows guarded crypto only inside the two measured CosmJS modules', () => {
    const guarded = [
      '//#region node_modules/@cosmjs/crypto/build/random.js',
      'const crypto = __require("crypto");',
      '//#endregion',
    ].join('\n');
    expect(findNodeOnlyImports(guarded)).toEqual([]);
    expect(findNodeOnlyImports('const crypto = __require("crypto");')).toEqual([
      expect.objectContaining({ specifier: 'crypto' }),
    ]);
  });
});
