import { readFileSync } from 'node:fs';
import { rolldown } from 'rolldown';
import { describe, expect, it } from 'vitest';

/**
 * The REAL `default:null`-chain guard (B1-secondary; ENG-309).
 *
 * The Node-run barrel-hygiene tests (`../src/index.test.ts`) resolve under the `node`
 * condition, so they PASS even if a browser-safe barrel statically pulls a module whose
 * browser resolution is `default:null` (core's `/guarded-fetch`, agent-core's
 * `/guarded-fetch`). That failure is invisible to vitest and to dependency-cruiser
 * (`doNotFollow:node_modules`). The ONLY thing that catches it is an actual
 * browser-condition bundle: `platform:'browser'` defaults `conditionNames` to
 * `['import','browser','default']` (the `node` condition is NOT applied), so a
 * `default:null` mapping throws a resolution error mid-bundle.
 *
 * This bundles EACH browser-safe SDK subpath entry from `dist/` and asserts the build
 * SUCCEEDS; each node-only entry must REJECT. Requires `dist/` built first
 * (`npm run build -w @manifest-network/manifest-sdk`).
 *
 * (The full browser BUILD + node-builtin string-scan + size budget stay Plan B; this is
 * the minimal fence-verification.)
 */

/** Package root, the base the `exports` map's `./dist/*.js` paths are relative to. */
const PKG_ROOT = new URL('../', import.meta.url);

type Entry = { subpath: string; file: string };

/**
 * Split the SDK's subpath entries by what `package.json` itself says about browser resolution
 * (ENG-644). DERIVED, never hand-listed: a hand-maintained entry list silently stops covering a
 * newly added subpath, which is the drift that made the dependency-cruiser DAG rules vacuous
 * (ENG-641). The discriminator is not a convention — `default: null` IS the browser fence, the
 * exact mapping that makes browser resolution throw, so a new entry lands on the correct side by
 * construction.
 */
function subpathEntries(): { browserSafe: Entry[]; nodeOnly: Entry[] } {
  const { exports } = JSON.parse(
    readFileSync(new URL('package.json', PKG_ROOT), 'utf8'),
  ) as { exports: Record<string, unknown> };

  const browserSafe: Entry[] = [];
  const nodeOnly: Entry[] = [];
  for (const [subpath, conditions] of Object.entries(exports)) {
    // `./package.json` maps to a bare string, not a condition object — not a JS entry.
    if (typeof conditions !== 'object' || conditions === null) continue;
    const {
      import: esm,
      node,
      default: fallback,
    } = conditions as Record<string, unknown>;
    // Take the file from the MAPPING, not from the subpath name — the two need not agree, and
    // assuming `dist/<subpath>.js` would quietly bundle the wrong file (or a missing one).
    const file = [esm, node].find((c) => typeof c === 'string') as
      | string
      | undefined;
    if (!file) continue;
    (fallback === null ? nodeOnly : browserSafe).push({ subpath, file });
  }
  return { browserSafe, nodeOnly };
}

const { browserSafe: BROWSER_SAFE, nodeOnly: NODE_ONLY } = subpathEntries();

describe('manifest-sdk browser resolution (no default:null chain)', () => {
  // Anti-vacuity: every assertion below is generated by a loop, so a derivation that silently
  // returned nothing would register ZERO tests and the file would pass green having checked
  // nothing — the precise failure mode this suite exists to prevent.
  it('derives both entry sets from package.json exports (neither is empty)', () => {
    expect(BROWSER_SAFE.length).toBeGreaterThan(0);
    expect(NODE_ONLY.length).toBeGreaterThan(0);
  });

  for (const { subpath, file } of BROWSER_SAFE) {
    it(`${subpath} resolves under browser conditions`, async () => {
      const bundle = await rolldown({
        input: new URL(file, PKG_ROOT).pathname,
        // platform:'browser' => resolve.conditionNames defaults to ['import','browser','default']
        // for import statements; the 'node' condition is NOT applied, so a browser-safe barrel
        // that ever pulls a `{node,default:null}` subpath throws a resolution error here.
        platform: 'browser',
      });
      try {
        await expect(bundle.generate({ format: 'esm' })).resolves.toBeDefined();
      } finally {
        await bundle.close(); // always close, even if generate() rejects (matches the /node control)
      }
    });
  }

  // POSITIVE CONTROL (MAJOR-3): the whole guard rests on rolldown HARD-FAILING a `default:null`
  // browser resolution. Each node-only entry IS such a case (`/node` re-exports core's
  // `{node,default:null}` /guarded-fetch). Bundling one under browser conditions MUST reject — if a
  // future rolldown/tsdown bump ever demotes that to a soft warning, this fails LOUDLY instead of
  // letting the positive assertions above pass vacuously. Derived alongside BROWSER_SAFE, so a new
  // node-only subpath gets its control for free rather than being silently uncontrolled.
  for (const { subpath, file } of NODE_ONLY) {
    it(`${subpath} REJECTS under browser conditions (proves the default:null guard still bites)`, async () => {
      await expect(
        (async () => {
          const bundle = await rolldown({
            input: new URL(file, PKG_ROOT).pathname,
            platform: 'browser',
          });
          try {
            await bundle.generate({ format: 'esm' });
          } finally {
            await bundle.close();
          }
        })(),
      ).rejects.toThrow();
    });
  }
});
