import { readFileSync } from 'node:fs';
import { rolldown } from 'rolldown';
import { describe, expect, it } from 'vitest';

/**
 * The REAL `default:null`-chain guard (B1-secondary; ENG-309).
 *
 * The Node-run barrel-hygiene tests (`../src/index.test.ts`) resolve under the `node`
 * condition, so they PASS even if a browser-safe barrel statically pulls a module whose
 * browser resolution is `default:null` (core's `/guarded-fetch`, agent-core's
 * `/guarded-fetch`). That failure is invisible to vitest and to dependency-cruiser
 * (`doNotFollow:node_modules`). The ONLY thing that catches it is an actual
 * browser-condition bundle: `platform:'browser'` defaults `conditionNames` to
 * `['import','browser','default']` (the `node` condition is NOT applied), so a
 * `default:null` mapping throws a resolution error mid-bundle.
 *
 * This bundles EACH browser-safe SDK subpath through its public package specifier and
 * asserts that the build succeeds without an unguarded Node import; each node-only entry
 * must reject. Requires `dist/` built first
 * (`npm run build -w @manifest-network/manifest-sdk`).
 */

/** Package root, the base the `exports` map's `./dist/*.js` paths are relative to. */
const PKG_ROOT = new URL('../', import.meta.url);

type Entry = { subpath: string; specifier: string };

// @cosmjs/crypto's guarded optional require("crypto") degrades to a pure-JS
// implementation in browsers. All other unresolved imports fail closed.
const ALLOWLISTED_WARNINGS = [/@cosmjs\/crypto/];

const NODE_IMPORT =
  /(?:from|require\(|import\()\s*['"](?:node:[a-z_/]+|fs|path|http|https|net|tls|stream|os|async_hooks|undici|ws|crypto-browserify|process\/browser|stream-browserify)['"]/;

/**
 * Split the SDK's subpath entries by what `package.json` itself says about browser resolution
 * (ENG-644). DERIVED, never hand-listed: a hand-maintained entry list silently stops covering a
 * newly added subpath, which is the drift that made the dependency-cruiser DAG rules vacuous
 * (ENG-641). The discriminator is not a convention — `default: null` IS the browser fence, the
 * exact mapping that makes browser resolution throw, so a new entry lands on the correct side by
 * construction.
 */
function subpathEntries(): { browserSafe: Entry[]; nodeOnly: Entry[] } {
  const { name, exports } = JSON.parse(
    readFileSync(new URL('package.json', PKG_ROOT), 'utf8'),
  ) as { name: string; exports: Record<string, unknown> };

  const browserSafe: Entry[] = [];
  const nodeOnly: Entry[] = [];
  for (const [subpath, conditions] of Object.entries(exports)) {
    // `./package.json` maps to a bare string, not a condition object — not a JS entry.
    if (typeof conditions !== 'object' || conditions === null) continue;
    const {
      import: esm,
      node,
      default: fallback,
    } = conditions as Record<string, unknown>;
    // Require a concrete runtime target. The bundle itself resolves the public specifier so the
    // package map — including its browser fence — remains part of the test.
    const target = [esm, node].find(
      (condition) => typeof condition === 'string',
    ) as string | undefined;
    if (!target) continue;
    const specifier = subpath === '.' ? name : `${name}${subpath.slice(1)}`;
    (fallback === null ? nodeOnly : browserSafe).push({
      subpath,
      specifier,
    });
  }
  return { browserSafe, nodeOnly };
}

const { browserSafe: BROWSER_SAFE, nodeOnly: NODE_ONLY } = subpathEntries();

async function bundleEntry(
  specifier: string,
  onLog?: (level: string, log: { code?: string; message?: string }) => void,
): Promise<string> {
  const bundle = await rolldown({
    input: specifier,
    platform: 'browser',
    onLog,
  });
  try {
    const { output } = await bundle.generate({ format: 'esm' });
    return output
      .filter((item) => item.type === 'chunk')
      .map((item) => item.code)
      .join('\n');
  } finally {
    await bundle.close();
  }
}

describe('manifest-sdk browser resolution + Node-builtin hygiene', () => {
  // Anti-vacuity: every assertion below is generated by a loop, so a derivation that silently
  // returned nothing would register ZERO tests and the file would pass green having checked
  // nothing — the precise failure mode this suite exists to prevent.
  it('derives both entry sets from package.json exports (neither is empty)', () => {
    expect(BROWSER_SAFE.length).toBeGreaterThan(0);
    expect(NODE_ONLY.length).toBeGreaterThan(0);
  });

  for (const { subpath, specifier } of BROWSER_SAFE) {
    it(`${subpath} bundles cleanly under browser conditions`, async () => {
      const warnings: string[] = [];
      const code = await bundleEntry(specifier, (_level, log) => {
        if (log.code === 'UNRESOLVED_IMPORT') {
          warnings.push(log.message ?? String(log));
        }
      });
      const unallowed = warnings.filter(
        (warning) =>
          !ALLOWLISTED_WARNINGS.some((allowed) => allowed.test(warning)),
      );

      expect(unallowed).toEqual([]);
      const leak = code.match(NODE_IMPORT);
      expect(leak, leak?.[0]).toBeNull();
    });
  }

  // POSITIVE CONTROL (MAJOR-3): the whole guard rests on rolldown HARD-FAILING a `default:null`
  // browser resolution. Each node-only entry IS such a case in the SDK package map. Bundling one
  // through its public specifier under browser conditions MUST reject — if a
  // future rolldown/tsdown bump ever demotes that to a soft warning, this fails LOUDLY instead of
  // letting the positive assertions above pass vacuously. Derived alongside BROWSER_SAFE, so a new
  // node-only subpath gets its control for free rather than being silently uncontrolled.
  for (const { subpath, specifier } of NODE_ONLY) {
    it(`${subpath} REJECTS under browser conditions (proves the default:null guard still bites)`, async () => {
      await expect(bundleEntry(specifier)).rejects.toThrow();
    });
  }
});
